dist: bionic
language: python
python:
  - "2.7"

before_install: true

install:
    - pip install coverage
      pip install coveralls

addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - ninja-build

script:
    - gcc -dumpfullversion
    - src/test/runalltests.sh

after_success:
    - coveralls
